export const ROUTE_PATHS = {
  public: {
    home: '/',
    about: '/about',
    programs: '/programs',
    programDetails: (programId = ':programId') => `/programs/${programId}`,
    coaches: '/coaches',
    coachProfile: (coachId = ':coachId') => `/coaches/${coachId}`,
    locations: '/locations',
    pricing: '/pricing',
    offers: '/offers',
    gallery: '/gallery',
    events: '/events',
    eventDetails: (eventId = ':eventId') => `/events/${eventId}`,
    blog: '/blog',
    blogPost: (postId = ':postId') => `/blog/${postId}`,
    contact: '/contact',
    registerChild: '/register-child',
    bookTrial: '/book-trial',
    terms: '/terms',
    privacy: '/privacy',
  },
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    forgotPassword: '/auth/forgot-password',
  },
  parent: {
    dashboard: '/parent',
    children: '/parent/children',
    childProfile: (childId = ':childId') => `/parent/children/${childId}`,
    childAttendance: (childId = ':childId') =>
      `/parent/children/${childId}/attendance`,
    childProgress: (childId = ':childId') => `/parent/children/${childId}/progress`,
    subscriptions: '/parent/subscriptions',
    payments: '/parent/payments',
    invoices: '/parent/invoices',
    makeUpRequest: '/parent/make-up-request',
    messages: '/parent/messages',
    documents: '/parent/documents',
    settings: '/parent/settings',
  },
  coach: {
    dashboard: '/coach',
    todaySessions: '/coach/today-sessions',
    students: '/coach/students',
    attendance: '/coach/attendance',
    assessments: '/coach/assessments',
    progressNotes: '/coach/progress-notes',
    incidentReport: '/coach/incident-report',
    schedule: '/coach/schedule',
    settings: '/coach/settings',
  },
  admin: {
    dashboard: '/admin',
    students: '/admin/students',
    studentNew: '/admin/students/new',
    studentDetail: (studentId = ':studentId') => `/admin/students/${studentId}`,
    studentEdit: (studentId = ':studentId') => `/admin/students/${studentId}/edit`,
    parents: '/admin/parents',
    coaches: '/admin/coaches',
    coachNew: '/admin/coaches/new',
    coachDetail: (coachId = ':coachId') => `/admin/coaches/${coachId}`,
    coachEdit: (coachId = ':coachId') => `/admin/coaches/${coachId}/edit`,
    programs: '/admin/programs',
    programNew: '/admin/programs/new',
    programDetail: (programId = ':programId') => `/admin/programs/${programId}`,
    programEdit: (programId = ':programId') => `/admin/programs/${programId}/edit`,
    sports: '/admin/sports',
    branches: '/admin/branches',
    branchNew: '/admin/branches/new',
    branchDetail: (branchId = ':branchId') => `/admin/branches/${branchId}`,
    branchEdit: (branchId = ':branchId') => `/admin/branches/${branchId}/edit`,
    schedule: '/admin/schedule',
    scheduleNew: '/admin/schedule/new',
    scheduleEdit: (sessionId = ':sessionId') => `/admin/schedule/${sessionId}/edit`,
    scheduleDetail: (sessionId = ':sessionId') => `/admin/schedule/${sessionId}`,

    attendance: '/admin/attendance',
    attendanceMark: '/admin/attendance/mark',
    finance: '/admin/finance',
    financeSubscriptions: '/admin/finance/subscriptions',
    financeSubscriptionDetails: '/admin/finance/subscriptions/:subscriptionId',
    financePayments: '/admin/finance/payments',
    financeInvoices: '/admin/finance/invoices',
    financeInvoiceDetails: '/admin/finance/invoices/:invoiceId',
    financePaymentDetails: '/admin/finance/payments/:paymentId',
    financeSubscriptionNew: '/admin/finance/subscriptions/new',
    financeSubscriptionEdit: '/admin/finance/subscriptions/:subscriptionId/edit',
    financeInvoiceNew: '/admin/finance/invoices/new',
    financeInvoiceEdit: '/admin/finance/invoices/:invoiceId/edit',
    financePaymentNew: '/admin/finance/payments/new',
    financePaymentEdit: '/admin/finance/payments/:paymentId/edit',

    offers: '/admin/offers',
    coupons: '/admin/coupons',
    events: '/admin/events',
    camps: '/admin/camps',
    leads: '/admin/leads',
    trialRequests: '/admin/trial-requests',
    reports: '/admin/reports',
    notifications: '/admin/notifications',
    cms: '/admin/cms',
    cmsHome: '/admin/cms/home',
    cmsGallery: '/admin/cms/gallery',
    users: '/admin/users',
    rolesPermissions: '/admin/roles-permissions',
    settings: '/admin/settings',
    auditLogs: '/admin/audit-logs',
  },
} as const;

export const ROLE_HOME_PATH: Record<
  Exclude<import('@/types').Role, 'guest'>,
  string
> = {
  parent: ROUTE_PATHS.parent.dashboard,
  coach: ROUTE_PATHS.coach.dashboard,
  accountant: ROUTE_PATHS.admin.finance,
  admin: ROUTE_PATHS.admin.dashboard,
};
