import type {
  CoachAssignedPlayerDto,
  CoachAttendanceTrendPointDto,
  CoachIncidentReportDto,
  CoachProfileDto,
  CoachProgressNoteDto,
  CoachSessionDto,
  CoachSkillAssessmentDto,
  CoachTaskDto,
} from '@/features/coach/types/coach.dto';

export const coachChartColors = {
  blue: '#00129B',
  yellow: '#FFD400',
  green: '#16A34A',
  red: '#DC2626',
  orange: '#F97316',
  purple: '#7C3AED',
  slate: '#64748B',
};

export const currentCoachMock: CoachProfileDto = {
  id: 'coach-omar',
  name: 'Coach Omar',
  specialization: 'Football Development',
  branch: 'Dubai Main Branch',
  levels: ['Intermediate', 'Advanced'],
  rating: 4.8,
};

export const coachTodaySessionsMock: CoachSessionDto[] = [
  {
    id: 'session-001',
    assignedCoachIds: ['coach-omar'],
    title: 'Football U10 Technical Training',
    program: 'Football Development',
    branch: 'Dubai Main Branch',
    court: 'Pitch A',
    time: '04:00 PM',
    duration: '90 min',
    level: 'Intermediate',
    status: 'attendancePending',
    assignedPlayers: 18,
    attendanceMarked: 0,
    capacity: 20,
  },
  {
    id: 'session-002',
    assignedCoachIds: ['coach-omar'],
    title: 'Football U12 Match Simulation',
    program: 'Football Development',
    branch: 'Dubai Main Branch',
    court: 'Pitch B',
    time: '06:00 PM',
    duration: '90 min',
    level: 'Advanced',
    status: 'scheduled',
    assignedPlayers: 16,
    attendanceMarked: 0,
    capacity: 18,
  },
  {
    id: 'session-003',
    assignedCoachIds: ['coach-omar'],
    title: 'Football U8 Fundamentals',
    program: 'Football Development',
    branch: 'Dubai Main Branch',
    court: 'Pitch C',
    time: '07:30 PM',
    duration: '60 min',
    level: 'Beginner',
    status: 'scheduled',
    assignedPlayers: 14,
    attendanceMarked: 0,
    capacity: 16,
  },
  {
    id: 'session-999',
    assignedCoachIds: ['coach-sara'],
    title: 'Restricted Swimming Session',
    program: 'Swimming Academy',
    branch: 'Dubai Main Branch',
    court: 'Pool A',
    time: '09:00 AM',
    duration: '60 min',
    level: 'Intermediate',
    status: 'scheduled',
    assignedPlayers: 10,
    attendanceMarked: 0,
    capacity: 12,
  },
];

export const coachUpcomingSessionsMock: CoachSessionDto[] = [
  {
    id: 'session-004',
    assignedCoachIds: ['coach-omar'],
    title: 'Football U10 Passing Accuracy',
    program: 'Football Development',
    branch: 'Dubai Main Branch',
    court: 'Pitch A',
    time: 'Tomorrow · 05:00 PM',
    duration: '90 min',
    level: 'Intermediate',
    status: 'scheduled',
    assignedPlayers: 17,
    attendanceMarked: 0,
    capacity: 20,
  },
  {
    id: 'session-005',
    assignedCoachIds: ['coach-omar'],
    title: 'Football U12 Defensive Shape',
    program: 'Football Development',
    branch: 'Dubai Main Branch',
    court: 'Pitch B',
    time: 'Friday · 06:30 PM',
    duration: '90 min',
    level: 'Advanced',
    status: 'scheduled',
    assignedPlayers: 15,
    attendanceMarked: 0,
    capacity: 18,
  },
];

export const coachAssignedPlayersMock: CoachAssignedPlayerDto[] = [
  {
    id: 'player-001',
    assignedCoachIds: ['coach-omar'],
    name: 'Omar Khaled',
    age: 9,
    program: 'Football Development',
    group: 'U10 Technical Group',
    branch: 'Dubai Main Branch',
    level: 'Intermediate',
    status: 'excellent',
    parentName: 'Khaled Al Mansouri',
    attendanceRate: 92,
    progressScore: 84,
    skillScore: 86,
    sessionsAttended: 23,
    totalSessions: 25,
    lastSession: '2026-06-02',
    nextSession: '2026-06-05 · 04:00 PM',
    latestNote:
      'Strong passing accuracy and teamwork. Shows consistent focus during possession drills.',
    coachRecommendation:
      'Keep developing first touch under pressure and encourage quick decision-making.',
    strengths: ['Passing accuracy', 'Teamwork', 'Short possession'],
    improvementAreas: ['First touch under pressure', 'Body positioning'],
    skills: [
      { name: 'Passing', score: 88, status: 'excellent' },
      { name: 'Ball Control', score: 82, status: 'good' },
      { name: 'Positioning', score: 79, status: 'good' },
      { name: 'Fitness', score: 85, status: 'good' },
    ],
  },
  {
    id: 'player-002',
    assignedCoachIds: ['coach-omar'],
    name: 'Yousef Khaled',
    age: 11,
    program: 'Football Development',
    group: 'U12 Advanced Group',
    branch: 'Dubai Main Branch',
    level: 'Advanced',
    status: 'needsFollowUp',
    parentName: 'Khaled Al Mansouri',
    attendanceRate: 74,
    progressScore: 78,
    skillScore: 77,
    sessionsAttended: 17,
    totalSessions: 23,
    lastSession: '2026-05-29',
    nextSession: '2026-06-06 · 06:00 PM',
    latestNote:
      'Needs consistency in attendance and positioning during defensive transitions.',
    coachRecommendation:
      'Follow up on attendance consistency and give targeted defensive positioning drills.',
    strengths: ['Physical effort', 'Shooting power', 'Competitive attitude'],
    improvementAreas: [
      'Attendance consistency',
      'Defensive positioning',
      'Transition awareness',
    ],
    skills: [
      { name: 'Shooting', score: 84, status: 'good' },
      { name: 'Positioning', score: 72, status: 'needsWork' },
      { name: 'Decision Making', score: 76, status: 'good' },
      { name: 'Fitness', score: 80, status: 'good' },
    ],
  },
  {
    id: 'player-003',
    assignedCoachIds: ['coach-omar'],
    name: 'Ali Mansour',
    age: 8,
    program: 'Football Development',
    group: 'U8 Fundamentals',
    branch: 'Dubai Main Branch',
    level: 'Beginner',
    status: 'active',
    parentName: 'Mansour Ali',
    attendanceRate: 88,
    progressScore: 80,
    skillScore: 79,
    sessionsAttended: 22,
    totalSessions: 25,
    lastSession: '2026-06-02',
    nextSession: '2026-06-05 · 07:30 PM',
    latestNote:
      'Improving ball control and confidence. Responds well to simple visual instructions.',
    coachRecommendation:
      'Continue confidence-building drills and use short game-based activities.',
    strengths: ['Confidence', 'Balance', 'Ball familiarity'],
    improvementAreas: ['Coordination speed', 'Listening during transitions'],
    skills: [
      { name: 'Ball Control', score: 80, status: 'good' },
      { name: 'Balance', score: 84, status: 'good' },
      { name: 'Coordination', score: 76, status: 'good' },
      { name: 'Confidence', score: 82, status: 'good' },
    ],
  },
  {
    id: 'player-004',
    assignedCoachIds: ['coach-omar'],
    name: 'Hamdan Saeed',
    age: 10,
    program: 'Football Development',
    group: 'U10 Technical Group',
    branch: 'Dubai Main Branch',
    level: 'Intermediate',
    status: 'excellent',
    parentName: 'Saeed Hamdan',
    attendanceRate: 95,
    progressScore: 90,
    skillScore: 91,
    sessionsAttended: 24,
    totalSessions: 25,
    lastSession: '2026-06-02',
    nextSession: '2026-06-05 · 04:00 PM',
    latestNote:
      'Excellent effort, tactical awareness, and communication with teammates.',
    coachRecommendation:
      'Introduce more advanced tactical challenges and leadership moments during drills.',
    strengths: ['Tactical awareness', 'Communication', 'Work rate'],
    improvementAreas: ['Weak foot passing', 'Finishing under pressure'],
    skills: [
      { name: 'Passing', score: 92, status: 'excellent' },
      { name: 'Awareness', score: 91, status: 'excellent' },
      { name: 'Communication', score: 90, status: 'excellent' },
      { name: 'Finishing', score: 84, status: 'good' },
    ],
  },
  {
    id: 'player-005',
    assignedCoachIds: ['coach-omar'],
    name: 'Rashed Nasser',
    age: 12,
    program: 'Football Development',
    group: 'U12 Advanced Group',
    branch: 'Dubai Main Branch',
    level: 'Advanced',
    status: 'active',
    parentName: 'Nasser Rashed',
    attendanceRate: 86,
    progressScore: 82,
    skillScore: 83,
    sessionsAttended: 19,
    totalSessions: 22,
    lastSession: '2026-06-01',
    nextSession: '2026-06-06 · 06:00 PM',
    latestNote:
      'Good defensive reading under pressure and improving passing decisions.',
    coachRecommendation:
      'Increase match simulation exposure and encourage quicker scanning before receiving.',
    strengths: ['Defensive reading', 'Composure', 'Tackling timing'],
    improvementAreas: ['Scanning', 'Forward passing speed'],
    skills: [
      { name: 'Defending', score: 86, status: 'good' },
      { name: 'Passing', score: 80, status: 'good' },
      { name: 'Scanning', score: 76, status: 'good' },
      { name: 'Fitness', score: 84, status: 'good' },
    ],
  },
  {
    id: 'student-999',
    assignedCoachIds: ['coach-sara'],
    name: 'Restricted Student',
    age: 10,
    program: 'Swimming Academy',
    group: 'Swimming Group A',
    branch: 'Dubai Main Branch',
    level: 'Intermediate',
    status: 'active',
    parentName: 'Hidden Parent',
    attendanceRate: 90,
    progressScore: 82,
    skillScore: 83,
    sessionsAttended: 20,
    totalSessions: 22,
    lastSession: '2026-06-02',
    nextSession: '2026-06-05 · 09:00 AM',
    latestNote: 'Hidden from this coach.',
    coachRecommendation: 'Restricted from current coach scope.',
    strengths: [],
    improvementAreas: [],
    skills: [],
  },
];

export const coachTasksMock: CoachTaskDto[] = [
  {
    id: 'task-001',
    coachId: 'coach-omar',
    title: 'Mark attendance for U10 session',
    description: 'Attendance is still pending for the 04:00 PM session.',
    priority: 'high',
    due: 'Today',
    href: '/coach/attendance',
  },
  {
    id: 'task-002',
    coachId: 'coach-omar',
    title: 'Add progress notes',
    description: '3 assigned players need updated progress notes this week.',
    priority: 'medium',
    due: 'This week',
    href: '/coach/progress-notes',
  },
  {
    id: 'task-003',
    coachId: 'coach-omar',
    title: 'Review incident follow-up',
    description: 'One low-severity incident needs admin review update.',
    priority: 'medium',
    due: 'Tomorrow',
    href: '/coach/incidents',
  },
];

export const coachAttendanceTrendMock: CoachAttendanceTrendPointDto[] = [
  { day: 'Mon', attendance: 88, completion: 100 },
  { day: 'Tue', attendance: 91, completion: 100 },
  { day: 'Wed', attendance: 84, completion: 92 },
  { day: 'Thu', attendance: 89, completion: 100 },
  { day: 'Fri', attendance: 93, completion: 100 },
  { day: 'Sat', attendance: 86, completion: 88 },
];

export const coachProgressNotesMock: CoachProgressNoteDto[] = [
  {
    id: 'note-001',
    studentId: 'player-001',
    sessionId: 'session-001',
    coachId: 'coach-omar',
    date: '2026-06-02',
    type: 'development',
    priority: 'medium',
    visibility: 'adminParent',
    rating: 4,
    title: 'Passing and teamwork improvement',
    note:
      'Omar showed better timing in short passes and communicated well with teammates during possession drills.',
    recommendation:
      'Add more one-touch passing drills under light pressure during the next session.',
    followUpRequired: false,
  },
  {
    id: 'note-002',
    studentId: 'player-002',
    sessionId: 'session-002',
    coachId: 'coach-omar',
    date: '2026-05-29',
    type: 'followUp',
    priority: 'high',
    visibility: 'adminParent',
    rating: 3,
    title: 'Defensive transition follow-up',
    note:
      'Yousef needs more support in transition positioning after losing possession.',
    recommendation:
      'Use repeated defensive recovery drills and short feedback breaks.',
    followUpRequired: true,
  },
  {
    id: 'note-003',
    studentId: 'player-003',
    sessionId: 'session-003',
    coachId: 'coach-omar',
    date: '2026-06-02',
    type: 'skill',
    priority: 'medium',
    visibility: 'coachOnly',
    rating: 4,
    title: 'Confidence improvement',
    note:
      'Ali was more confident during ball-control games and responded well to visual instructions.',
    recommendation:
      'Keep using simple competitive games to build confidence and coordination.',
    followUpRequired: false,
  },
  {
    id: 'note-004',
    studentId: 'player-004',
    sessionId: 'session-001',
    coachId: 'coach-omar',
    date: '2026-06-01',
    type: 'development',
    priority: 'low',
    visibility: 'adminParent',
    rating: 5,
    title: 'Leadership and tactical awareness',
    note:
      'Hamdan showed excellent communication, leadership, and tactical awareness in group drills.',
    recommendation:
      'Introduce more advanced tactical challenges and leadership tasks.',
    followUpRequired: false,
  },
];
export const coachSkillAssessmentsMock: CoachSkillAssessmentDto[] = [
  {
    id: 'assessment-001',
    studentId: 'player-001',
    coachId: 'coach-omar',
    date: '2026-06-02',
    skillName: 'Passing',
    category: 'technical',
    currentScore: 88,
    targetScore: 92,
    status: 'excellent',
    note: 'Accurate short passing and good timing in possession drills.',
    recommendation: 'Add more one-touch passing drills under light pressure.',
  },
  {
    id: 'assessment-002',
    studentId: 'player-001',
    coachId: 'coach-omar',
    date: '2026-06-02',
    skillName: 'Ball Control',
    category: 'technical',
    currentScore: 82,
    targetScore: 88,
    status: 'good',
    note: 'Good control, but needs more practice under pressure.',
    recommendation: 'Use tight-space receiving drills and short passing sequences.',
  },
  {
    id: 'assessment-003',
    studentId: 'player-002',
    coachId: 'coach-omar',
    date: '2026-05-29',
    skillName: 'Positioning',
    category: 'tactical',
    currentScore: 72,
    targetScore: 84,
    status: 'needsWork',
    note: 'Needs stronger defensive positioning and better recovery runs.',
    recommendation: 'Use repeated defensive transition drills and short feedback breaks.',
  },
  {
    id: 'assessment-004',
    studentId: 'player-003',
    coachId: 'coach-omar',
    date: '2026-06-02',
    skillName: 'Confidence',
    category: 'mental',
    currentScore: 82,
    targetScore: 88,
    status: 'good',
    note: 'More confident with the ball and responds well to visual instructions.',
    recommendation: 'Continue game-based drills and positive reinforcement.',
  },
  {
    id: 'assessment-005',
    studentId: 'player-004',
    coachId: 'coach-omar',
    date: '2026-06-01',
    skillName: 'Tactical Awareness',
    category: 'tactical',
    currentScore: 91,
    targetScore: 94,
    status: 'excellent',
    note: 'Excellent decision-making, communication, and tactical reading.',
    recommendation: 'Introduce more advanced leadership and tactical challenge moments.',
  },
  {
    id: 'assessment-006',
    studentId: 'player-005',
    coachId: 'coach-omar',
    date: '2026-06-01',
    skillName: 'Defending',
    category: 'physical',
    currentScore: 86,
    targetScore: 91,
    status: 'good',
    note: 'Good defensive reading under pressure and improving tackling timing.',
    recommendation: 'Increase match simulation exposure and recovery-position drills.',
  },
];

export const coachIncidentReportsMock: CoachIncidentReportDto[] = [
  {
    id: 'incident-001',
    studentId: 'player-002',
    sessionId: 'session-002',
    coachId: 'coach-omar',
    date: '2026-06-03',
    type: 'behavior',
    severity: 'medium',
    status: 'underReview',
    title: 'Repeated disruption during tactical drill',
    description:
      'Student repeatedly interrupted instructions during a tactical drill and needed individual redirection.',
    immediateAction:
      'Coach paused the activity, spoke calmly with the student, and moved him to a smaller group for closer supervision.',
    adminNotified: true,
    parentFollowUpRequired: true,
    reviewedByAdmin: true,
    resolutionNote:
      'Admin will monitor the next two sessions and follow up if behavior continues.',
  },
  {
    id: 'incident-002',
    studentId: 'player-003',
    sessionId: 'session-003',
    coachId: 'coach-omar',
    date: '2026-06-04',
    type: 'safety',
    severity: 'low',
    status: 'resolved',
    title: 'Minor slip during warm-up',
    description:
      'Student slipped during a warm-up movement. No serious concern was observed, but the area was checked.',
    immediateAction:
      'Coach stopped the drill briefly, checked the student, and adjusted the warm-up area before continuing.',
    adminNotified: true,
    parentFollowUpRequired: false,
    reviewedByAdmin: true,
    resolutionNote:
      'Resolved. Continue normal training with standard supervision.',
  },
  {
    id: 'incident-003',
    studentId: 'player-001',
    sessionId: 'session-001',
    coachId: 'coach-omar',
    date: '2026-06-02',
    type: 'equipment',
    severity: 'low',
    status: 'closed',
    title: 'Training cone placement issue',
    description:
      'A cone line was too close to the sideline and created a movement constraint during the drill.',
    immediateAction:
      'Coach adjusted the layout and reminded students to wait for instructions before starting the drill.',
    adminNotified: false,
    parentFollowUpRequired: false,
    reviewedByAdmin: false,
    resolutionNote: 'Closed by coach. No further action required.',
  },
];